import { CameraFormData } from '@/types/camera.types'

export const DETECTION_CLASSES = {
    // RFDETR COCO Dataset
    // 1: "person",
    // 2: "bicycle",
    // 3: "car",
    // 4: "motorcycle",
    // 5: "airplane",
    // 6: "bus",
    // 7: "train",
    // 8: "truck",
    // 9: "boat",
    // 10: "traffic light",
    // 11: "fire hydrant",
    // 13: "stop sign",
    // 14: "parking meter",
    // 15: "bench",
    // 16: "bird",
    // 17: "cat",
    // 18: "dog",
    // 19: "horse",
    // 20: "sheep",
    // 21: "cow",
    // 22: "elephant",
    // 23: "bear",
    // 24: "zebra",
    // 25: "giraffe",
    // 27: "backpack",
    // 28: "umbrella",
    // 31: "handbag",
    // 32: "tie",
    // 33: "suitcase",
    // 34: "frisbee",
    // 35: "skis",
    // 36: "snowboard",
    // 37: "sports ball",
    // 38: "kite",
    // 39: "baseball bat",
    // 40: "baseball glove",
    // 41: "skateboard",
    // 42: "surfboard",
    // 43: "tennis racket",
    // 44: "bottle",
    // 46: "wine glass",
    // 47: "cup",
    // 48: "fork",
    // 49: "knife",
    // 50: "spoon",
    // 51: "bowl",
    // 52: "banana",
    // 53: "apple",
    // 54: "sandwich",
    // 55: "orange",
    // 56: "broccoli",
    // 57: "carrot",
    // 58: "hot dog",
    // 59: "pizza",
    // 60: "donut",
    // 61: "cake",
    // 62: "chair",
    // 63: "couch",
    // 64: "potted plant",
    // 65: "bed",
    // 67: "dining table",
    // 70: "toilet",
    // 72: "tv",
    // 73: "laptop",
    // 74: "mouse",
    // 75: "remote",
    // 76: "keyboard",
    // 77: "cell phone",
    // 78: "microwave",
    // 79: "oven",
    // 80: "toaster",
    // 81: "sink",
    // 82: "refrigerator",
    // 84: "book",
    // 85: "clock",
    // 86: "vase",
    // 87: "scissors",
    // 88: "teddy bear",
    // 89: "hair drier",
    // 90: "toothbrush"

   // YOLO Coco Dataset
    // 0: "person",
    // 1: "bicycle",
    // 2: "car",
    // 3: "motorcycle",
    // 4: "airplane",
    // 5: "bus",
    // 6: "train",
    // 7: "truck",
    // 8: "boat",
    // 9: "traffic light",
    // 10: "fire hydrant",
    // 11: "stop sign",
    // 12: "parking meter",
    // 13: "bench",
    // 14: "bird",
    // 15: "cat",
    // 16: "dog",
    // 17: "horse",
    // 18: "sheep",
    // 19: "cow",
    // 20: "elephant",
    // 21: "bear",
    // 22: "zebra",
    // 23: "giraffe",
    // 24: "backpack",
    // 25: "umbrella",
    // 26: "handbag",
    // 27: "tie",
    // 28: "suitcase",
    // 29: "frisbee",
    // 30: "skis",
    // 31: "snowboard",
    // 32: "sports ball",
    // 33: "kite",
    // 34: "baseball bat",
    // 35: "baseball glove",
    // 36: "skateboard",
    // 37: "surfboard",
    // 38: "tennis racket",
    // 39: "bottle",
    // 40: "wine glass",
    // 41: "cup",
    // 42: "fork",
    // 43: "knife",
    // 44: "spoon",
    // 45: "bowl",
    // 46: "banana",
    // 47: "apple",
    // 48: "sandwich",
    // 49: "orange",
    // 50: "broccoli",
    // 51: "carrot",
    // 52: "hot dog",
    // 53: "pizza",
    // 54: "donut",
    // 55: "cake",
    // 56: "chair",
    // 57: "couch",
    // 58: "potted plant",
    // 59: "bed",
    // 60: "dining table",
    // 61: "toilet",
    // 62: "tv",
    // 63: "laptop",
    // 64: "mouse",
    // 65: "remote",
    // 66: "keyboard",
    // 67: "cell phone",
    // 68: "microwave",
    // 69: "oven",
    // 70: "toaster",
    // 71: "sink",
    // 72: "refrigerator",
    // 73: "book",
    // 74: "clock",
    // 75: "vase",
    // 76: "scissors",
    // 77: "teddy bear",
    // 78: "hair drier",
    // 79: "toothbrush"
  
    // 0: "Normal Vehicle",
    // 1: "Vehicular Accident",
    // 2: "Bicycle",
    // 3: "Bus",
    // 4: "Car",
    // 5: "Motorcycle",
    // 6: "Cars",
    // 7: "Truck",
    // 8: "Cars",
    // 9: "Mini Bus",
    // 10: "Mobil",
    // 11: "Mobil Box",
    // 12: "Mobil Pickup",
    // 13: "Mobil Van",
    // 14: "Motobike",
    // 15: "Motorbike",
    // 16: "Motorbike",
    // 17: "Truck"
    1:"Accident",
    2:"Bicycle",
    3:"Bus",
    4:"Car",
    5:"License Plate",
    6:"Motorcycle",
    7:"Non Accident",
    8:"Truck",
    9:"With Helmet",
    10:"Without Helmet"
    
} as const



export const INITIAL_FORM_DATA: CameraFormData = {
  name: '',
  type: '',
  url: '',
  description: '',
  odthreshold: 50,
  is_detection: false,
  odclasses: [],
  encoder: '',
  resolution: '1920x1080',
  fps: 30,
  rectype: ''
}

export const CAMERA_TYPES = ['RTSP', 'HTTP', 'Youtube Live'] as const

export const RECORDING_TYPES = [
  { value: 'continuous', label: 'Continuous' },
  { value: 'motion', label: 'Motion Detection' },
  { value: 'none', label: 'None' },
] as const

export const ENCODER_TYPES = [
  { value: 'h264', label: 'H.264' },
  { value: 'h265', label: 'H.265 (HEVC)' },
  { value: 'mjpeg', label: 'MJPEG' },
  { value: 'vp8', label: 'VP8' },
  { value: 'vp9', label: 'VP9' }
] as const

export const RESOLUTION_OPTIONS = [
  { value: '640x480', label: '640x480 (VGA)' },
  { value: '1280x720', label: '1280x720 (HD)' },
  { value: '1920x1080', label: '1920x1080 (Full HD)' },
  { value: '2560x1440', label: '2560x1440 (2K)' },
  { value: '3840x2160', label: '3840x2160 (4K)' }
] as const

export const FPS_OPTIONS = [
  { value: 5, label: '5 FPS' },
  { value: 15, label: '15 FPS' },
  { value: 24, label: '24 FPS' },
  { value: 30, label: '30 FPS' },
  { value: 60, label: '60 FPS' }
] as const