create table public.camera (
  id bigint generated by default as identity not null,
  name text null,
  type text null,
  url text null,
  description text null,
  odthredshold integer null,
  is_detection boolean null default false,
  odclasses text null,
  encoder text null,
  resolution text null,
  fps integer null,
  rectype text null,
  constraint camera_pkey primary key (id)
) TABLESPACE pg_default;

create table public.general_settings (
  id serial not null,
  user_id uuid null,
  signaling_protocol text null default 'ws'::text,
  signaling_ip text null,
  signaling_port text null,
  signaling_name text null,
  datetime_enabled boolean null default true,
  datetime_format text null default 'YYYY-MM-DD HH:mm:ss'::text,
  updated_at timestamp with time zone null default now(),
  constraint general_settings_pkey primary key (id),
  constraint general_settings_user_id_unique unique (user_id),
  constraint general_settings_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;


create table public.object_detection_events (
  id bigserial not null,
  camera_id integer not null,
  camera_name text not null,
  camera_url text null,
  timestamp timestamp with time zone not null default now(),
  object_class_id integer not null,
  object_class_name text not null,
  confidence real not null,
  bbox_x real not null default 0,
  bbox_y real not null default 0,
  bbox_width real not null default 0,
  bbox_height real not null default 0,
  frame_width integer not null default 0,
  frame_height integer not null default 0,
  session_id uuid null,
  detection_metadata jsonb null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  constraint object_detection_events_pkey primary key (id),
  constraint object_detection_events_confidence_check check (
    (
      (confidence >= (0)::double precision)
      and (confidence <= (1)::double precision)
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_detection_events_camera_id on public.object_detection_events using btree (camera_id) TABLESPACE pg_default;

create index IF not exists idx_detection_events_timestamp on public.object_detection_events using btree ("timestamp") TABLESPACE pg_default;

create index IF not exists idx_detection_events_object_class on public.object_detection_events using btree (object_class_name) TABLESPACE pg_default;

create index IF not exists idx_detection_events_camera_timestamp on public.object_detection_events using btree (camera_id, "timestamp") TABLESPACE pg_default;

create index IF not exists idx_detection_events_session on public.object_detection_events using btree (session_id) TABLESPACE pg_default;

ALTER TABLE object_detection_events 
ADD COLUMN IF NOT EXISTS image_url TEXT;

CREATE INDEX IF NOT EXISTS idx_object_detection_events_image_url 
ON object_detection_events(image_url) 
WHERE image_url IS NOT NULL;


create table public.profiles (
  id uuid not null,
  username text null,
  avatar_url text null,
  updated_at timestamp with time zone null default now(),
  full_name text null,
  website text null,
  constraint profiles_pkey primary key (id),
  constraint profiles_username_key unique (username),
  constraint profiles_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;


create table public.system_logs (
  id bigserial not null,
  timestamp timestamp with time zone not null default now(),
  level character varying(20) not null,
  category character varying(50) not null,
  subcategory character varying(50) null,
  source_file character varying(255) null,
  source_function character varying(255) null,
  line_number integer null,
  message text not null,
  details jsonb null,
  camera_id integer null,
  camera_url text null,
  session_id uuid null,
  client_id text null,
  stack_trace text null,
  performance_metrics jsonb null,
  resolved boolean null default false,
  resolution_notes text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint system_logs_pkey primary key (id),
  constraint system_logs_camera_id_fkey foreign KEY (camera_id) references camera (id)
) TABLESPACE pg_default;


CREATE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, website, avatar_url)
  VALUES (NEW.id, NEW.raw_user_meta_data->>'username', NEW.raw_user_meta_data->>'website', NEW.raw_user_meta_data->>'avatar_url');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();



ALTER TABLE "public"."camera" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."general_settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."object_detection_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."system_logs" ENABLE ROW LEVEL SECURITY;

create policy "camera_policy" on "public"."camera" as PERMISSIVE for ALL to anon, authenticated using (true) with check (true);
create policy "general_settings_policy" on "public"."general_settings" as PERMISSIVE for ALL to anon, authenticated using (true) with check (true);
create policy "object_detection_events_policy" on "public"."object_detection_events" as PERMISSIVE for ALL to anon, authenticated using (true) with check (true);
create policy "profiles_policy" on "public"."profiles" as PERMISSIVE for ALL to anon, authenticated using (true) with check (true);
create policy "system_logs_policy" on "public"."system_logs" as PERMISSIVE for ALL to anon, authenticated using (true) with check (true);


-- Create storage schema tables (these need to exist before Storage API starts)
CREATE TABLE IF NOT EXISTS storage.buckets (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    owner UUID,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    public BOOLEAN DEFAULT FALSE,
    avif_autodetection BOOLEAN DEFAULT FALSE,
    file_size_limit BIGINT,
    allowed_mime_types TEXT[],
    CONSTRAINT buckets_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS storage.objects (
    id UUID PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
    bucket_id TEXT,
    name TEXT,
    owner UUID,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    last_accessed_at TIMESTAMPTZ DEFAULT NOW(),
    metadata JSONB,
    path_tokens TEXT[] GENERATED ALWAYS AS (string_to_array(name, '/')) STORED,
    version TEXT,
    CONSTRAINT objects_bucketid_objname_key UNIQUE(bucket_id, name),
    CONSTRAINT objects_bucket_id_fkey FOREIGN KEY (bucket_id) REFERENCES storage.buckets(id)
);

-- Create storage bucket for recordings (PUBLIC)
INSERT INTO storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types,
    created_at,
    updated_at
) 
SELECT
    'vitcam-recordings',
    'vitcam-recordings',
    TRUE,
    52428800,
    ARRAY['video/mp4', 'video/webm', 'video/quicktime', 'image/jpeg', 'image/png', 'image/webp']::text[],
    NOW(),
    NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM storage.buckets WHERE id = 'vitcam-recordings'
);

-- Create storage bucket for recordings (PUBLIC)
INSERT INTO storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types,
    created_at,
    updated_at
) 
SELECT
    'detection-images',
    'detection-images',
    TRUE,
    NULL,
    ARRAY['image/*']::text[],
    NOW(),
    NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM storage.buckets WHERE id = 'detection-images'
);



-- Enable RLS on storage objects
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
ALTER TABLE storage.buckets ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Allow authenticated uploads to vitcam-recordings" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated reads from vitcam-recordings" ON storage.objects;
DROP POLICY IF EXISTS "Allow public reads from vitcam-recordings" ON storage.objects;

DROP POLICY IF EXISTS "Allow authenticated uploads to detection-images" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated reads from detection-images" ON storage.objects;
DROP POLICY IF EXISTS "Allow public reads from detection-images" ON storage.objects;

DROP POLICY IF EXISTS "Allow authenticated updates to own files" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated deletes of own files" ON storage.objects;
DROP POLICY IF EXISTS "Service role has full access" ON storage.objects;
DROP POLICY IF EXISTS "Allow public bucket access" ON storage.buckets;

-- Create RLS policies for the bucket vitcam-recordings
-- Allow public (anonymous) read access
CREATE POLICY "Allow public reads from vitcam-recordings"
ON storage.objects FOR SELECT
TO anon, authenticated
USING (bucket_id = 'vitcam-recordings');

-- Allow authenticated users to upload vitcam-recordings
CREATE POLICY "Allow authenticated uploads to vitcam-recordings"
ON storage.objects FOR INSERT
TO anon, authenticated
WITH CHECK (bucket_id = 'vitcam-recordings');

-- Allow authenticated users to update their own files vitcam-recordings
CREATE POLICY "Allow authenticated updates to own files vitcam-recordings"
ON storage.objects FOR UPDATE
TO anon, authenticated
USING (bucket_id = 'vitcam-recordings');

-- Allow authenticated users to delete their own files vitcam-recordings
CREATE POLICY "Allow authenticated deletes of own files vitcam-recordings"
ON storage.objects FOR DELETE
TO anon, authenticated
USING (bucket_id = 'vitcam-recordings');


-- Create RLS policies for the bucket detection-images
-- Allow public (anonymous) read access
CREATE POLICY "Allow public reads from detection-images"
ON storage.objects FOR SELECT
TO anon, authenticated
USING (bucket_id = 'detection-images');

-- Allow authenticated users to upload detection-images
CREATE POLICY "Allow authenticated uploads to detection-images"
ON storage.objects FOR INSERT
TO anon, authenticated
WITH CHECK (bucket_id = 'detection-images');

-- Allow authenticated users to update their own files detection-images
CREATE POLICY "Allow authenticated updates to own files detection-images"
ON storage.objects FOR UPDATE
TO anon, authenticated
USING (bucket_id = 'detection-images');

-- Allow authenticated users to delete their own files detection-images
CREATE POLICY "Allow authenticated deletes of own files detection-images"
ON storage.objects FOR DELETE
TO anon, authenticated
USING (bucket_id = 'detection-images');



-- Service role has full access to everything
CREATE POLICY "Service role has full access"
ON storage.objects FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- Allow reading bucket information
CREATE POLICY "Allow public bucket access"
ON storage.buckets FOR SELECT
TO anon, authenticated
USING (true);

-- Create a function to automatically set updated_at
CREATE OR REPLACE FUNCTION storage.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create triggers for updated_at
DROP TRIGGER IF EXISTS set_updated_at ON storage.buckets;
CREATE TRIGGER set_updated_at
    BEFORE UPDATE ON storage.buckets
    FOR EACH ROW
    EXECUTE FUNCTION storage.handle_updated_at();

DROP TRIGGER IF EXISTS set_updated_at ON storage.objects;
CREATE TRIGGER set_updated_at
    BEFORE UPDATE ON storage.objects
    FOR EACH ROW
    EXECUTE FUNCTION storage.handle_updated_at();


ALTER TABLE object_detection_events 
ADD COLUMN tracker_id INTEGER;

CREATE INDEX idx_tracker_id ON object_detection_events(tracker_id);


-- ============================================================================
-- Database Indexes for Analytics Pagination - SUPABASE VERSION
-- ============================================================================
-- Purpose: Create essential indexes for pagination optimization
-- Usage: Copy and paste this entire script into Supabase SQL Editor and run
-- Safe to run multiple times (uses IF NOT EXISTS)
-- ============================================================================

-- Index 1: Primary timestamp index (MOST IMPORTANT for pagination)
-- This is critical for fast ORDER BY timestamp queries
CREATE INDEX IF NOT EXISTS idx_events_timestamp 
ON object_detection_events(timestamp DESC);

-- Index 2: Camera + timestamp composite index
-- Used when filtering by camera_id with pagination
CREATE INDEX IF NOT EXISTS idx_events_camera_timestamp 
ON object_detection_events(camera_id, timestamp DESC);

-- Index 3: Object class + timestamp composite index
-- Used when filtering by object_class_name with pagination
CREATE INDEX IF NOT EXISTS idx_events_object_timestamp 
ON object_detection_events(object_class_name, timestamp DESC);

-- Index 4: Camera name + timestamp composite index
-- Used when filtering by camera_name with pagination
CREATE INDEX IF NOT EXISTS idx_events_camera_name_timestamp 
ON object_detection_events(camera_name, timestamp DESC);

-- Index 5: Covering index (optional but recommended)
-- Includes frequently accessed columns for index-only scans
CREATE INDEX IF NOT EXISTS idx_events_covering 
ON object_detection_events(timestamp DESC, camera_id, object_class_name, confidence)
INCLUDE (camera_name, tracker_id, bbox_x, bbox_y, bbox_width, bbox_height);

-- Update table statistics for query optimization
ANALYZE object_detection_events;
